# Generated by Django 4.0.6 on 2022-07-24 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField()),
                ('source_version', models.IntegerField()),
                ('source_raw', models.TextField()),
                ('source_compiled', models.TextField()),
                ('source_pyteal_version', models.IntegerField(blank=True, null=True)),
                ('source_type', models.CharField(choices=[('TL', 'Teal'), ('PT', 'PyTeal'), ('RH', 'Reach')], default='TL', max_length=2)),
                ('source_pyteal_mode', models.CharField(blank=True, choices=[('SIG', 'Signature'), ('APP', 'Application')], default='APP', max_length=3, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.app')),
            ],
        ),
    ]
