# Generated by Django 4.0.6 on 2022-08-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='source_approval',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appversion',
            name='source_clear_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appversion',
            name='source_compiled_approval',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appversion',
            name='source_compiled_clear',
            field=models.TextField(blank=True, null=True),
        ),
    ]
