# Generated by Django 4.0.6 on 2022-08-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_appversion_source_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='source_approval_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appversion',
            name='source_clear_state_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
