# Generated by Django 4.0.6 on 2022-08-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_appversion_source_approval_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appversion',
            name='source_raw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appversion',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
