# Generated by Django 4.0.6 on 2022-08-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_appversion_source_raw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='source_decompiled_approval',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appversion',
            name='source_decompiled_clear',
            field=models.TextField(blank=True, null=True),
        ),
    ]
