# Generated by Django 4.0.6 on 2022-08-16 20:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_appversion_source_decompiled_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appversion',
            name='verified_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
